name: Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # peaceiris/actions-gh-pages needs this permission

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Check formatting
        # bunx is the equivalent of npx
        run: bunx @biomejs/biome check .

      - name: Build project
        run: bun run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
