name: Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write # peaceiris/actions-gh-pages needs this permission

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Build project
        run: bun run build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          VITE_SUI_FULLNODE_URL: https://fullnode.devnet.sui.io
          VITE_SUI_DEVNET_FAUCET: https://faucet.devnet.sui.io
          VITE_SUI_PROVER_DEV_ENDPOINT: https://prover-dev.mystenlabs.com/v1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
